// Auth
export const LOADING_GET_USER_TYPE = 'LOADING_GET_USER_TYPE';
export const GOT_USER_TYPE = 'GOT_USER_TYPE';
export const GOT_USER_TYPE_FAILED = 'GOT_USER_TYPE_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// change password
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// Error handling and feedback UI reports
export const CREATE_MESSAGES = 'CREATE_MESSAGES';
export const API_MESSSAGE = 'API_MESSSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// Battalion Two CRUD
export const BATTALLION_TWO_CREATE = 'BATTALLION_TWO_CREATE';
export const BATTALLION_TWO_CREATE_LOADING = 'BATTALLION_TWO_CREATE_LOADING';
export const BATTALLION_TWO_CREATED = 'BATTALLION_TWO_CREATED';

// Fetching battalion two data
export const BATTALION_TWO_OVERRALL_FETCHED = 'BATTALION_TWO_OVERRALL_FETCHED';
export const BATTALION_THREE_OVERRALL_FETCHED = 'BATTALION_THREE_OVERRALL_FETCHED';
export const BATTALION_ONE_OVERRALL_FETCHED = 'BATTALION_ONE_OVERRALL_FETCHED';
export const BATTALION_TWO_DATA_FETCHED = 'BATTALION_TWO_DATA_FETCHED';
export const BATTALION_TWO_DATA_LOADING = 'BATTALION_TWO_DATA_LOADING';

export const BATTALION_TWO_DETAIL_LOADING = 'BATTALION_TWO_DETAIL_LOADING';
export const BATTALION_TWO_DETAIL_FETCHED = 'BATTALION_TWO_DETAIL_FETCHED';

export const BATTALION_TWO_QUERY_LOADING = 'BATTALION_TWO_QUERY_LOADING';
export const BATTALION_TWO_QUERY_FETCHED = 'BATTALION_TWO_QUERY_FETCHED';
export const BATTALION_TWO_QUERY_FAILED = 'BATTALION_TWO_QUERY_FAILED';

// Fetching battalion one data
export const BATTALION_ONE_DATA_LOADING = 'BATTALION_ONE_DATA_LOADING';
export const BATTALION_ONE_DATA_FETCHED = 'BATTALION_ONE_DATA_FETCHED';

// Fetching battalion three data
export const BATTALION_THREE_DATA_LOADING = 'BATTALION_THREE_DATA_LOADING';
export const BATTALION_THREE_DATA_FETCHED = 'BATTALION_THREE_DATA_FETCHED';

export const BATTALION_THREE_DETAIL_LOADING = 'BATTALION_THREE_DETAIL_LOADING';
export const BATTALION_THREE_DETAIL_FETCHED = 'BATTALION_THREE_DETAIL_FETCHED';

export const BATTALION_FOUR_DATA_FETCHED = 'BATTALION_FOUR_DATA_FETCHED';
export const BATTALION_FOUR_DATA_LOADING = 'BATTALION_FOUR_DATA_LOADING';

export const BATTALION_FIVE_DATA_LOADING = 'BATTALION_FIVE_DATA_LOADING';
export const BATTALION_FIVE_DATA_FETCHED = 'BATTALION_FIVE_DATA_FETCHED';

export const BATTALION_SIX_DATA_LOADING = 'BATTALION_SIX_DATA_LOADING';
export const BATTALION_SIX_DATA_FETCHED = 'BATTALION_SIX_DATA_FETCHED';

export const BATTALLION_THREE_CREATE_LOADING = 'BATTALLION_THREE_CREATE_LOADING';
export const BATTALLION_THREE_CREATED = 'BATTALLION_THREE_CREATED';

export const BATTALION_ONE_DETAIL_LOADING = 'BATTALION_ONE_DETAIL_LOADING';
export const BATTALION_ONE_DETAIL_FETCHED = 'BATTALION_ONE_DETAIL_FETCHED';

export const BATTALION_FOUR_OVERRALL_FETCHED = 'BATTALION_FOUR_OVERRALL_FETCHED';
export const BATTALION_FIVE_OVERRALL_FETCHED = 'BATTALION_FIVE_OVERRALL_FETCHED';
export const BATTALION_SIX_OVERRALL_FETCHED = 'BATTALION_SIX_OVERRALL_FETCHED';

export const BATTALION_GENERAL_DETAIL_LOADING = 'BATTALION_GENERAL_DETAIL_LOADING';
export const BATTALION_GENERAL_DETAIL_FETCHED = 'BATTALION_GENERAL_DETAIL_FETCHED';

export const BATTALLION_GENERAL_CREATE_LOADING = 'BATTALLION_GENERAL_CREATE_LOADING';
export const BATTALLION_GENERAL_CREATED = 'BATTALLION_GENERAL_CREATED';

export const BATTALION_GENERAL_DEPARTEMENT_QUERY_LOADING = 'BATTALION_GENERAL_DEPARTEMENT_QUERY_LOADING';
export const BATTALION_GENERAL_DEPARTEMENT_QUERY_FETCHED = 'BATTALION_GENERAL_DEPARTEMENT_QUERY_FETCHED';
export const BATTALION_GENERAL_DEPARTEMENT_QUERY_FAILED = 'BATTALION_GENERAL_DEPARTEMENT_QUERY_FAILED';

export const BATTALION_SECTION_QUERY_LOADING = 'BATTALION_SECTION_QUERY_LOADING';
export const BATTALION_SECTION_QUERY_FETCHED = 'BATTALION_SECTION_QUERY_FETCHED';
 
export const BATTALION3_DEPARTEMENT_QUERY_LOADING = 'BATTALION3_DEPARTEMENT_QUERY_LOADING';
export const BATTALION3_DEPARTEMENT_QUERY_FETCHED = 'BATTALION3_DEPARTEMENT_QUERY_FETCHED';
export const BATTALION3_DEPARTEMENT_QUERY_FAILED = 'BATTALION3_DEPARTEMENT_QUERY_FAILED';

export const GENERATE_REPORT_BATTALLION_TWO_LOADING = 'GENERATE_REPORT_BATTALLION_TWO_LOADING';
export const GENERATE_REPORT_BATTALLION_TWO_DONE = 'GENERATE_REPORT_BATTALLION_TWO_DONE';

export const DELETE_RECORD_LOADING = 'DELETE_RECORD_LOADING';
export const DELETE_RECORD_LOADED = 'DELETE_RECORD_LOADED';
export const DELETE_RECORD_FALIED = 'DELETE_RECORD_FALIED';

export const DELETE_LOADING = 'DELETE_LOADING';
export const DELETE_LOADED = 'DELETE_LOADED';
export const DELETE_FALIED = 'DELETE_FALIED';

export const VIPPU_OVERRALL_FETCHED = 'VIPPU_OVERRALL_FETCHED';


// access 
export const ADMIN_REQUEST_ACCESS_LOADING = 'ADMIN_REQUEST_ACCESS_LOADING';
export const ADMIN_REQUEST_ACCESS_SUCCESS = 'ADMIN_REQUEST_ACCESS_SUCCESS';
export const ADMIN_REQUEST_ACCESS_FAIL = 'ADMIN_REQUEST_ACCESS_FAIL';
export const ADMIN_LOGOUT_LOADING = 'ADMIN_LOGOUT_LOADING';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';

